auto: true
server: true
permalink: none

title: "feathers"
description: "Feathers is a jekyll boilerplate for building static clients for (JSON RESTful) APIs."
copyright: 'Copyright © 2013'

url: "http://localhost:4000"
apiurl: "https://api.github.com"

exclude:
- .gitignore
- README.md
- TUTORIALS.md