auto: true
server: true
permalink: none
url: "http://localhost:4000"
apiurl: "https://api.github.com/gists"
exclude:
- .gitignore
- README.md
- Makefile
- Rakefile
- component.json
- components

title: "Jekyll boilerplate"
description: "Jekyll boilerplate"