auto: true
server: true
permalink: none
url: "http://localhost:4000"
# API
apiurl: "https://api.github.com/gists"

title: "feathers"
description: "Feathers is a jekyll boilerplate for building static clients for (JSON RESTful) APIs."
exclude:
- .gitignore
- README.md