this["JST"] = this["JST"] || {};

this["JST"][["errorPage"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<h2>Error 404</h2>\n<p>We\'re truly sorry, but there is no such page.</p>';}return __p};

this["JST"][["mainLayout"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<nav id=\'menu\'></nav>\n<section id=\'content\'></section>';}return __p};

this["JST"][["message"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<a class=\'close\'>x</a>\n' +((__t = ( message )) == null ? '' : __t);}return __p};

this["JST"][["profileForm"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<h1>Profile</h1>\n<div class=\'body\'>\n    <div class=\'field\'>\n        <label for=\'name\'>Name</label>\n        <input autofocus=\'autofocus\' id=\'name\' name=\'name\' type=\'text\' value=\'' +((__t = ( name )) == null ? '' : __t) +'\'>\n    </div>\n    <div class=\'field\'>\n        <label for=\'email\'>Email</label>\n        <input id=\'email\' name=\'email\' type=\'email\' value=\'' +((__t = ( email )) == null ? '' : __t) +'\'>\n    </div>\n    <section>\n        <div class=\'field\'>\n            <label for=\'email\'>Email</label>\n            <input id=\'email\' name=\'email\' type=\'email\' value=\'' +((__t = ( email )) == null ? '' : __t) +'\'>\n        </div>\n    </section>\n</div>\n<div class=\'controls\'>\n    <a class=\'button\'>Save</a>\n</div>';}return __p};

this["JST"][["loggedHeader"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<a href=\'/\' id=\'home\'>{{ site.title }}</a>\n<a href=\'#servers\' id=\'servers\'>Servers</a>\n<a href=\'#help\' id=\'help\'>Help</a>\n<span class=\'minibutton\'>\n    <img src=' +((__t = ( 'http://www.gravatar.com/avatar/' + gravatarHash  + '?s=20' )) == null ? '' : __t) +' class=\'gravatar\'>\n    <span class=\'username\'>' +((__t = ( name )) == null ? '' : __t) +'</span>\n</span>\n<nav>\n    <a id=\'edit\' href=\'#profile\'>Edit</a>\n    <a id=\'logout\'>Logout</a>\n</nav>';}return __p};

this["JST"][["loginHeader"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<a href=\'#login\' id=\'home\'>{{ site.title }}</a>\n<a href=\'#help\' id=\'help\'>Help</a>';}return __p};

this["JST"][["loginForm"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<h1>Login in</h1>\n<div class=\'body\'>\n    <div class=\'field\'>\n        <label for=\'username\'>Username</label>\n        <input autofocus=\'autofocus\' id=\'username\' name=\'username\' type=\'text\'>\n    </div>\n    <div class=\'field\'>\n        <label for=\'password\'>Password</label>\n        <input id=\'password\' name=\'password\' type=\'password\'>        \n    </div>\n    <p class=\'help\'><a href=\'/password_resets\'>I forgot my password</a></p>\n</div>\n<div class=\'controls\'>\n    <a class=\'button\'>Login in</a>\n</div>';}return __p};

this["JST"][["serverDetail"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape, __j = Array.prototype.join;function print() { __p += __j.call(arguments, '') }with (obj) {__p += '<h1><strong>Name: </strong>' +((__t = ( name )) == null ? '' : __t) +'<span class=\'close\'>X</span></h1>\n<div class=\'body\'>\n    '; if (!_.isEmpty(services)) { ;__p += '\n        <ul class=\'services\'>\n            '; _.each(services, function(value, key) { ;__p += '\n                <li><strong>' +((__t = ( key )) == null ? '' : __t) +': ' +((__t = ( value )) == null ? '' : __t) +'</strong></li>\n            '; }); ;__p += '\n        </ul>\n    '; } ;__p += '\n    '; if (!_.isEmpty(provider)) { ;__p += '\n        <ul class=\'provider\'>\n            '; _.each(provider, function(value, key) { ;__p += '\n                <li><strong>' +((__t = ( key )) == null ? '' : __t) +': ' +((__t = ( value )) == null ? '' : __t) +'</strong></li>\n            '; }); ;__p += '\n        </ul>\n    '; } ;__p += '\n    '; if (!_.isEmpty(configuration)) { ;__p += '\n        <ul class=\'configuration\'>\n            '; _.each(configuration, function(value, key) { ;__p += '\n                <li><strong>' +((__t = ( key )) == null ? '' : __t) +': ' +((__t = ( value )) == null ? '' : __t) +'</strong></li>\n            '; }); ;__p += '\n        </ul>\n    '; } ;__p += '\n</div>';}return __p};

this["JST"][["serverEmpty"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<section class=\'intro\'>\n    <h2>Servers</h2>\n    <p class=\'description\'>Servers are instances of applications you want to manage, each associated with a unique URL. They may be different versions of the same application (for example development and production).</p>\n    <a class=\'primary button\'>Add a server</a>\n</section>';}return __p};

this["JST"][["serverIntro"]] = function(obj) {obj || (obj = {});var __t, __p = '', __e = _.escape;with (obj) {__p += '<h2><span class=\'status\'>' +((__t = ( status )) == null ? '' : __t) +'</span>' +((__t = ( name )) == null ? '' : __t) +'</h2>\n';}return __p};